schema_version = 1

[warp]
official_upstream = "86cfeb9006da7865d7f27f33228ed0f581d49f02"
integration_mirror = "8f38ae88e950bc1b339eb094b941e98032d5de59"
relative_path = "../warp"
remote = "git@github.com:lion1991/warp-nexshell.git"
